### ISSUE TITLE
Account for multiple WDPA assignements in clustered standard errors

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#105]
see @yotaae analysis [here](https://openkfw.github.io/mapme.protectedareas/map_cells_overlapping_wdpa.html)

Proposed Solutions:

- Create new standard errors cluster for each and every possible combination with mixed WDPAs 
- exclude the observations from the analysis.

**Comment by melvinhlwong** [comment]
This issue is now obsolet/adressed. 

We have figured that mulitple WDPA assignemnts is also adressed by analysing the impact of the financing not on the project level (that is multiple WDPA under one project) but by analysing each WDPA individually. Moreover, we drop any WDPA that is treated the second, third, or fourth time (or even more) from the analysis.
