### ISSUE TITLE
missing variable in matching frame

### ISSUE THREAD

**Issue by melvinhlwong** [openkfw/mapme.protectedareas#110]
@Jo-Schie 

Can you help out? I miss a variable that is crucial for the matching.

in /datadrive/datalake/mapme.protectedareas/output/matching/matching_frames/projects/matching_frame_199865056.rds
I miss the variable loss_tn. Without this, I cannot do the match for this dataset. I am not sure how many other datasets are affected but maybe you could check why it is not there for 199865056?

Strangely, everything works perfect for "199566829" and many other matching frames.

**Comment by Jo-Schie** [comment]
Most probable this happens because there is no prior  forest loss. The project you mention seems to be quite early. Please note that only projects from 2004 onwards will be candidates for this analysis. I suggest you eliminate all irrelevant projects in the first place looking at the project internal start date...

**Comment by melvinhlwong** [comment]
Thank you. that was exactly the reason. The first year of the BMZ project 199865056 is 2000 where there is not loss_tn calculated
